roslynpad/roslynpad

- src/RoslynPad.Common/Runtime/ResultObject.cs
- src/RoslynPad.Roslyn/RoslynPad.Roslyn.csproj
- src/RoslynPad.Roslyn/packages.config
- src/RoslynPad.RoslynEditor/RoslynPad.RoslynEditor.csproj
- src/RoslynPad.RoslynEditor/packages.config
- src/RoslynPad/RoslynPad.csproj
- src/RoslynPad/packages.config
Firstly I've updated Microsoft.CodeAnalysis references to the latest nightlies as the nightly versions in the master branch are no longer available on roslyn nightly NuGet.
I've added handling of reading properties in the tree results panel. An example of this is dumping the CurrentAppDomain. The properties will now say they've thrown an exception of [x] type.
> Exception handle property reads

- src/RoslynPad/MainWindow.xaml.cs
Use InvariantCulture when calling Rect.ToString() so that bounds are always persisted in invariant format: `"x,y,width,height"` instead of `"x;y;width;height"` (format depends on current culture)
Fixes `System.FormatException` when calling Rect.Parse(..) during app startup in LoadWindowLayout() on my machine.
> Fix FormatException during startup => Use InvariantCulture when calling Rect.ToString()

- src/RoslynPad.Roslyn/RoslynHost.cs
I need this argument so that I can provide default assemblies referenced as if via `#r`. Current parameter `additionalAssemblies` is used for other things and I couldn't find another way to do so. It is important that this parameter works with locations as strings and not another `IEnumerable<Assembly>`, otherwise unsigned assemblies will not work and will throw on loading into a signed process. The name `additionalDefaultReferencedAssemblyLocations` is very long but very precise on what it is :)
> Support additional default referenced assembly locations

- src/RoslynPad.Hosting/ExecutionHost.cs
- src/RoslynPad.Roslyn/Scripting/ScriptRunner.cs
Fixes #91. Just pop up the parameters as constructor args with default values.
> Expose CSharpCompilationOptions to ScriptRunner and ExecutionHost structors

- build/common.props
- src/RoslynPad.Roslyn/CodeFixes/CodeFixService.cs
- src/RoslynPad.Roslyn/Completion/Providers/AbstractLoadDirectiveCompletionProvider.cs
- src/RoslynPad.Roslyn/Completion/Providers/AbstractReferenceDirectiveCompletionProvider.cs
- src/RoslynPad.Roslyn/Completion/Providers/FileSystemCompletionHelper.cs
- src/RoslynPad.Roslyn/Completion/Providers/GlobalAssemblyCacheCompletionHelper.cs
- src/RoslynPad.Roslyn/RoslynPad.Roslyn.csproj
#178 This functionally works to support version 2.6.1 of Roslyn although there may be a better way of resolving the problems with FixAllState.Create being removed by MS.
> Updated to support Roslyn version 2.6.1

- src/RoslynPad.Editor.Windows.Test/RoslynPad.Editor.Windows.Test.csproj
- src/RoslynPad.Editor.Windows.Test/SearchReplacePanelTests.cs
- src/RoslynPad.Editor.Windows/SearchReplacePanel.cs
- src/RoslynPad.sln
Fixes #166
This is the issue I was aiming at when I came across #208 so I've branched off my solution for that.
I'll try to outline what I've done -
The `ISearchResult`s RoslynPad gets back from AvalonEdit already seem to support regex substitution, but we're casting them to `TextSegment`s and `TextSegment`s don't support regex substitution.
So I changed to storing the ISearchResults without casting them.
This meant they can no longer be stored in AvalonEdit's `TextSegmentCollection` which provided methods used by our `FindNext` / `FindPrevious` methods, so I've written tests for those and re-implemented them. 
The behaviour of `FindNext` / `FindPrevious` has changed very slightly e.g. if the caret is directly before a match and I press 'Find Next' then that match will now be selected …
> Regex substitution in Find & Replace

- src/RoslynPad.NetCore/MainWindow.xaml
- src/RoslynPad/App.xaml.cs
- src/RoslynPad/DocumentTreeView.xaml
Added some uniform bottom and top margins for the document tree view, and made the search bar buttons icons a bit bigger to make the icons crispier and added padding:
Left = before, Right = after
Old buttons hovered,
New ones: 
Also added the multicore JIT profile optimization to improve the startup time, the profile gets stored in the exe's folder with the name of `JitProfile.profile`.
Hope you like these changes :)
> Layout tweaks and multicore JIT for the WPF app.

- deploy/ZipPackage.ps1
* Change "\\" (backslash) to "/" in path at the moment of creating .zip file to fix MacOS unzip issue
Fixes: #249
> Fix MacOS unzip

- src/RoslynPad.Editor.Shared/RoslynOverloadProvider.cs
The overload insight window now will display a string such as "1 of 4" between the arrows when in the overload insight window.
Fixes #290
> Added display of selected overload index in Overload insight window.

- src/RoslynPad.Editor.Shared/ClassificationHighlightColors.cs
If someone want to implement custom color highlighting, it's difficult to reuse `ClassificationHighlightColors`.
The reason is that the internal `_map` is created in the ctor before anything can be customized in the inherited class ctor. This forces custom implementation to create another map by copy-pasting lot of the code of the original class.
This PR delays creation of the map so that the inheriting ctor has a chance to redefine some colors.
As a result, it's now possible to do things like this:
```csharp
class ClassificationHighlightColorsDark : ClassificationHighlightColors
{
public static readonly Color DefaultColor = Color.FromRgb(220, 220, 220);
public static readonly Color TypeColor = Color.FromRgb(78, 201, 176);
public static readonly Color KeywordColor = Color.FromRgb(86, 156, …
```
> ClassificationHighlightColors: create map lazily for easier customization in inherited class

- src/RoslynPad.Build/ExecutionHost.cs
Currently the path for MSBUILD restore is not escaped
This PR escapes the log path aswell as the project path.
> Fix msbuild not restoring nuget packages if path contains spaces.

- src/RoslynPad.Editor.Shared/CodeTextEditor.cs
fixes #268 by intoducing `private bool IsCharIdentifier(char c)` and using it on `RoslynPad.Editor.CodeTextEditor` to check if a entered character is a well-known identifier
Fixes the issue where a variable would be instantly completed when it contains an underscore `_` in it's name
Property to be completed:  
Pressing `_` without this fix:  
Pressing `_`  with the fix applied:
> Fix #268 - introduce IsCharIdentifier

- src/RoslynPad.Editor.Shared/SnippetManager.cs
Added snippet "desktopapp"
i test a lot of stuff using RoslynPad and sometimes need to create a Desktopapp-environment.
i guess this could be changed to only be visible in Windows-Builds (any directions on where to setup platform specific snippets?)
> Add code-snipped "desktopapp"

- src/RoslynPad.Build/ExecutionHostParameters.cs
- src/RoslynPad.Common.UI/ViewModels/OpenDocumentViewModel.cs
There seems to be a timing issue where the opened document is null while
the initial execution host parameters are created. This might not be the
best way, but making the `WorkingDirectory` writable and ensuring it
matches the current document WorkingDirectory seems to fix the issue
around relative path file loading.
Fix #350
> Ensure script execution WorkingDirectory matches current script path

- src/RoslynPad.Editor.Windows/RoslynPad.Editor.Windows.csproj
- src/RoslynPad.Roslyn.Windows/RoslynPad.Roslyn.Windows.csproj
This should have worked, but the temporary project created by
WPF still fails unless you have the .NET4.8 targeting pack :(
Might still be worth keeping as the underlying WPF issue might be
solved at some point?
> Ensure build succeeeds even without .net48 SDK

- src/RoslynPad.Editor.Shared/ContextActionsRenderer.cs
When moving the caret, the actions of the light bulb isn't automatically refreshed. Found a line of code that was commented, after uncommenting it worked again.
> Fixed issue where the lightbulb doesn't refresh automatically

- src/RoslynPad.Editor.Windows/CodeTextEditor.Windows.cs
I wanted to implemented a dark-mode theme for the editor, so I needed to customize search result highlight colors as white was not readable on bright green, so I'm storing and exposing the SearchReplacePanel as a property.
Please let me know if I'll need to make any changes.
Btw, the dark-mode theme can be found [in this gist](https://gist.github.com/gmanny/d40f71f0e38a6a9da673a2e05117b847). It's based on default Visual Studio colors.
> Exposed SearchReplacePanel of the Windows CodeTextEditor to allow its customization.

- src/RoslynPad/DocumentTreeView.xaml.cs
This will fix an issue when trying to open a folder from a documents pane (right click - open in file explorer). Currently the folder doesn't open.
Fixes #409
> Fix #409 "Open in Explorer doesn't work for folders"

- README.md
- src/RoslynPad.Common.UI/PlatformsFactory.cs
Hi,
I was facing problems running the RoslynPadNetCore on Linux because the default installation path with bash script it's the Home folder, so I'd suggest adding this path to search SDK.
The script to install on linux: [dotnet-install.sh](https://dot.net/v1/dotnet-install.sh) and the [docs](https://docs.microsoft.com/en-us/dotnet/core/install/linux?WT.mc_id=dotnet-35129-website#manual-installation).
Also, I've added the .zip with the last release with this fix here: [RoslynPadNetCore 15.1](https://github.com/luigihenrick/roslynpad/releases/tag/15.1) may be useful to someone else.
> Add home folder to search dotnet sdk

- src/RoslynPad.Build/ExecutionHost.cs
Fix #432 - Added ModuleInitializer attribute also for .NET Frameworks instead of considering only .NET Core below 5
When using the .NET Framework (x64) or (x86), the `Platform.FrameworkVersion` object is null
Therefore, the `ModuleInitializer `attribute is not added but we need it to avoid throwing an exception
This is why I added the condition "if Platform.IsFramework" in addition
`Platform.IsFramework` is only `true` for .NET versions and is `false` for .NET Core versions (and consequently also for .NET 5 and .NET 6 ;) )
> Fix #432 - Add the ModuleInitializer attribute also for .NET Frameworks

- src/RoslynPad.Common.UI/PlatformsFactory.cs
Some linux distributions (namely Fedora and possibly other rpm based distros) install dotnet core into `/usr/lib64/dotnet`. The path is currently missing in the collection of paths searched for the dotnet sdk.
Fixes #470
> Added /usr/lib64/dotnet to search path for the dotnet sdk

- src/RoslynPad.Runtime/RoslynPad.Runtime.csproj
Fixes `RoslynPad.Avalonia.sln` on Windows (tested in Rider).
The problem is that on Windows the following is being added in Directory.Build.props:
```xml
<UseWPF Condition=" $(MSBuildProjectName.Contains('Windows')) ">true</UseWPF>
<TargetFramework Condition=" '$(UseWPF)' == 'true' ">$(LtsTargetFramework)-windows</TargetFramework>
```
RoslynPad.Runtime.csproj is configured with TargetFrameworks:
```xml
<TargetFrameworks>$(EarliestSupportedTargetFramework);netstandard2.0</TargetFrameworks>
<TargetFrameworks Condition=" '$(DefaultTargetFramework)' != '$(EarliestSupportedTargetFramework)' ">$(DefaultTargetFramework);$(TargetFrameworks)</TargetFrameworks>
```
It seems that `<TargetFramework>` has higher priority than `<TargetFrameworks>`. Because of this the project is always being compiled …
> Fix RoslynPad.Avalonia on Windows

- global.json
- src/RoslynPad/MainWindow.xaml.cs
Related to https://github.com/roslynpad/roslynpad/issues/512
- Debug info for multiple monitors: [multiScreen.txt](https://github.com/roslynpad/roslynpad/files/14515063/multiScreen.txt)
- RoslynPad was moved onto attached monitor (not primary)
- Debug info for just primary monitor (built-in laptop screen): [SingleScreen.txt](https://github.com/roslynpad/roslynpad/files/14515089/SingleScreen.txt)
- Debug info when RoslynPad opened after being closed on secondary monitor and monitor was disconnected: [stuckOffScreen.txt](https://github.com/roslynpad/roslynpad/files/14515065/stuckOffScreen.txt)
- window does not seem to respond to `Win+<Arrow Keys>` short cuts to move window to remaining screen
Added a simple helper function based on …
> added logic to move window back onscreen if off screen on start

- src/RoslynPad.Avalonia/DocumentView.axaml.cs
- src/RoslynPad.Avalonia/FontFamilyValidator.cs
- src/RoslynPad.Common.UI/Services/ApplicationSettings.cs
- src/RoslynPad.Common.UI/Services/IApplicationSettingsValues.cs
- src/RoslynPad.Common.UI/Services/IFontFamilyValidator.cs
- src/RoslynPad.Common.UI/ViewModels/MainViewModel.cs
- src/RoslynPad/Controls/ILViewer.xaml
- src/RoslynPad/DocumentView.xaml
- src/RoslynPad/DocumentView.xaml.cs
- src/RoslynPad/FontFamilyValidator.cs
- src/RoslynPad/MainWindow.xaml
This PR moves the font family into the `RoslynPad.json` config to allow the user to override the value.
- A default value is generated depending on the hosts OS platform. On Windows, the default value is set to `Cascadia Code` (the current default) and if that Font Family is not available, it will default to `Consolas`.
- Seeing as `System.Drawing.FontFamily` is Windows only, a new interface was required to abstract out the font family validation to the corresponding UI Host (Avalonia, or WPF). 
- This fixes the issue #543 that crashes the RoslynPad UI if the `Cascadia Code` font family cannot be accessed for whatever reason. While the issue does not have a direct fix, allowing the user to change the font for the UI in the config will provide a way for users to mitigate the issue. (It …
> Fix #543 - Bind font family of editor and IL window to user config

- src/RoslynPad.Common.UI/PlatformsFactory.cs
improves #499 situation by including `/usr/lib/dotnet` path (enhancement).
> added usr/lib/dotnet path

- src/RoslynPad.Editor.Windows/Shared/CodeTextEditor.cs
Please reference an existing issue with one of the following labels:
* When `CompletionProvider.GetCompletionData()` returns no selected item, the first item is selected by default (consistent with Visual Studio behavior).
*  When triggering completion at `[StructLayout(`, the ScrollViewer correctly scrolls to `LayoutKind`  
<br/>
before:
after:
<br/>
before:
after:
If you would like to contribute something new, please discuss it in an issue first.
> Improve completion selection logic in CompletionWindow
